[programs.devnet]
buildspacesolana = "5Hu4WDZ6bJQoa4d4yvhD4UgPFc7jWqkBePQ1QCnGjsHM"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "devnet"
wallet = "/home/rahul/.config/solana/id.json"

[scripts]
test = "node tests/buildspacesolana.js"
